#!/bin/bash
# permanent process to stop the DAQ and check the webpage use
FILE=/home/root/daq/no_run
while true ; do
     NO_RUN=$(cat "$FILE" 2>/dev/null)

     if [ "X${NO_RUN}X" != XX ] ; then
        NOW=$(date +%s)
        if [ $((NOW-NO_RUN)) -gt 60 ] ; then
          # echo  "no_run Removed"
         rm "$FILE" 2>/dev/null    # file /daq/no_run is removed DAQ restart
         killall scope 2>/dev/null # to be sure that scope is closed
       fi

     fi

     sleep 5
 done
