#!/bin/sh
#written by R.Assiro - 10/2016
#mount flash partition MTD2 in /boot recovery volume
if df | grep -q /recovery$ ; then
  echo "/recovery volume already mounted"
  exit 0
fi

#echo -n "Attaching mtd2 partition... "
#ubidetach -p /dev/mtd2 2>/dev/null >/dev/null
#if ubiattach -p /dev/mtd2 >/dev/null ; then
#  echo OK
#else
#  echo "ERROR - Attaching mtd2 not possible"
#  exit 1
#fi

echo -n "Mounting ubi1:recovery on /recovery... "
if mount -t ubifs ubi1:recovery /recovery ; then
  echo OK
else
  echo "ERROR"
  exit 2
fi

