#!/bin/sh
#UPGRADE image.ub from linux ubuntu by tftp
echo "Upgrading UUB ..."
cd /var/ftp
tftp -g -l image.ub -r image.ub 172.16.17.198
echo "image.ub loaded"
tftp -g -l fpga.bit -r fpga.bit 172.16.17.198
echo "bitstream loaded"
ubiattach -p /dev/mtd2	
echo "MTD2 attached"
#mount -t ubifs ubi0:itbs /boot
echo "itbs volume mounted"
#cp image.ub /boot	
#cp fpga.bit /boot
#sync
#umount /boot
echo "unmount MTD2"
#ubidetach -p /dev/mtd2
echo "Please, reboot the system!"
